### ISSUE TITLE
Multiprocessing

### ISSUE THREAD

**Issue by HeadLessHUN** [PDAL/python-plugins#4]
Hello, i'm not really good at python scripting i'm trying to use filters.python to apply a median filter to cloud dimensions, and it works, but i wanted to speed things up a little bit with multiprocessing/multithreading. Threading won't help because still runs only on core, but i was not able to get multiprocessing to work on windows.

Do you happen to have a working example? Or do you have any other original way to apply median filter to any dimension like Red,Green,Blue,Intensity,etc.

**Comment by hobu** [comment]
GitHub tickets are not the appropriate venue for these kind of questions. Please join the mailing list and ask there. https://pdal.io/en/latest/community.html
