### ISSUE TITLE
filters.python not available after install pdal and pdal-plugins

### ISSUE THREAD

**Issue by dominikj2** [PDAL/python-plugins#9]
Although I have the below two packages in my venv:

python-pdal               3.4.5           py312h61d12cd_4    conda-forge
pdal-plugins              1.5.2                    pypi_0    pypi

I cant seem to find:

`libpdal_plugin_filter_python.dll`

in Library\lib and Library\bin of anaconda3\env. Using `pdal --drivers` confirms that I don't have **filters.python** which I would like to have to run a python function in a pipeline 
```
{
                "type": "filters.python",
                "script": "WF_Desktop_YOLO_V5.ipynb",  
                "function": "filter_by_treeID_min_z",
}
```

**Comment by hobu** [comment]
This is a configuration issue of conda forge. It is being tracked at https://github.com/conda-forge/python-pdal-feedstock/issues/124
